# Site settings
title: UX & Design studio for enterprise
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://www.100shapes.com"
twitter_username: 100Shapes
github_username:  100Shapes
permalink: /blog/:year/:month/:day/:title/

# 100 Shapes Settings
email: hello@100shapes.com
phone_number: +442037738175
phone_number_display: +44 203 773 8175

collections:
  - ventures
  - authors

# Build settings
markdown: kramdown
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - scripts
  - README.md
gems:
  - jekyll-feed
  - jekyll-less

