# Site settings
title: Design agency focused on educating
description: > # this means to ignore newlines until 'baseurl:'
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ''
url: 'http://www.100shapes.com'
instagram_username: '100shapes'
twitter_username: '@100Shapes'
github_username:  '@100Shapes'
address: '13 Hawley Cres., Camden, London, NW1 8NP'
address_link: https://goo.gl/maps/YVr9ih4MLZL2
permalink: /blog/:categories/:title/

# 100 Shapes Settings
email: hello@100shapes.com
phone_number: +442037738175
phone_number_display: +44 203 773 8175

menu:
  - label: Home
    link: /

  - label: UX & Enterprise
    link: /work/enterprise-ux/

  - label: Work
    link: /work/

  - label: Join us
    link: /join-us/

collections:
  projects:
    output: true
    permalink: /work/:path/

defaults:
  -
    scope:
      collection: projects
    values:
      layout: project

# Build settings
markdown: kramdown
safe: false

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  blanklines: false
  profile: false
  startings: [html, head, body]

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - scripts
  - README.md

gems:
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-paginate
