# Site settings
title: Design-driven business change
description: > # this means to ignore newlines until 'baseurl:'
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ''
url: 'http://www.100shapes.com'

address: '13 Hawley Crescent, NW1 8NP'
address_link: https://goo.gl/maps/YVr9ih4MLZL2
permalink: /blog/:categories/:title/

# 100 Shapes Settings
email: hello@100shapes.com
phone_number: +442037738175
phone_number_display: +44 203 773 8175
animation_in_classes: 'wow fadeIn'

menu:
  - label: UX & Enterprise
    link: /work/enterprise-ux/

  - label: Work
    link: /work/

  - label: Join us
    link: /join-us/

collections:
  projects:
    output: true
    permalink: /work/:path/

defaults:
  -
    scope:
      collection: projects
    values:
      layout: project

# Build settings
markdown: kramdown
safe: false

compress_html:
  clippings: all
  comments: all
  blanklines: false
  profile: false
  startings: [html, head, body]

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - scripts
  - README.md
  - package.json
  - webpack.config.js
  - node_modules
  - static/js
  - static/styles

gems:
  - jekyll-sitemap
  - jekyll-paginate
