# Site settings
title: UX design for business systems and digital products
description: > # this means to ignore newlines until 'baseurl:'
  100 Shapes designs enterprise systems, applications and other
  digital tools based on user experience (UX) principles for better
  business performance.
baseurl: ''
url: ''

address: '13 Hawley Crescent, NW1 8NP'
address_link: https://goo.gl/maps/YVr9ih4MLZL2
permalink: /blog/:categories/:title/

# 100 Shapes Settings
email: hello@100shapes.com
phone_number: +442037738175
phone_number_display: +44 203 773 8175
animation_in_classes: 'wow fadeIn'

menu:
  - label: Designing enterprise systems
    link: /work/designing-tools-for-business/

  - label: Work
    link: /work/

  - label: Blog
    link: /blog/

  - label: Join us
    link: /join-us/

collections:
  projects:
    output: true
    permalink: /work/:path/

defaults:
  -
    scope:
      collection: projects
    values:
      layout: project
  -
    scope:
      collection: posts
    values:
      medium_publication: ux-design-and-tech-blog


# Build settings
markdown: kramdown
safe: false

compress_html:
  clippings: all
  comments: all
  blanklines: false
  profile: false
  startings: [html, head, body]

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - scripts
  - README.md
  - package.json
  - webpack.config.js
  - node_modules
  - static/js
  - static/styles

gems:
  - jekyll-sitemap
